version: '3'
services:
  redis-server:
    image: 'redis'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ../nginx
    ports:
      - '3050:80'
  api:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    # ports:
    #   - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ../calculate-fibonacci
    # no need of ports because we are maniging using ngnix
    # ports:
    #   - '4000:80'
    volumes:
      - /app/node_modules
      - ../calculate-fibonacci:/app
  worker:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ../worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ../worker:/app

    