FROM node:14.14.0-alpine
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

# getting connect port issue in local


# Production

# FROM node:10-alpine as builder

# WORKDIR /app

# COPY ./package.json ./

# RUN npm install

# COPY . .

# RUN npm run build

# FROM nginx
# EXPOSE 4200
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=builder /app/build /usr/share/nginx/html
